name: pfam
description: Search for protein domains
keywords:
  - protein domains
  - functional annotation 

tools:
  - pfam:
      description: Search for protein domains
      homepage: https://github.com/SMRUCC/GCModeller/blob/master/src/interops/scripts/PfamScan/PfamScan/pfam_scan.pl



input:
  - inputfastaproteins:
      type: file
      description: |
        Fasta file containing the amino-acid sequences of the transcripts you wish to predict the existense of signal peptides. One transcript per row.

    

output:
  - pfam_out:
      type: file
      description: |
        Text file with results for each trascript of its protein domains.
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"


authors:
  - "@BiancaPasat"
