name: probscan
description: Predict propability of specific structure.
keywords:
  - probscan

tools:
  - probscan:
      description: Predict propability of specific structure.
      tool_dev_url:
      doi: ""
      licence: 


input:
  - sequences:
      type: file
      description: |
        Fasta file containing the fasta of the RNA molecules you wish to predict their secondary structure.




output:
  - probscan_out:
      type: file
      description: |
        Whole output of probscan algorithm.


  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"


authors:
  - "@BiancaPasat"
