name: mcia
description: Multiple co-inertia analysis
keywords:
  - integration of omics
  - multiple co-inertia analysis
tools:
  - mcia:
      description: Differential gene expression analysis based on the negative binomial distribution.
      homepage: https://bioconductor.org/packages/release/bioc/html/omicade4.html
      documentation: https://bioconductor.org/packages/release/bioc/vignettes/omicade4/inst/doc/omicade4.pdf
      tool_dev_url: None
      doi: ""
      licence: ["GPL (>= 2)"]


input:
  - pgenes:
      type: file
      description: |
        Wait for genes analysis. 
  - pmirna:
      type: file
      description: |
        Wait for mirna analysis. 
   - pproteins:
      type: file
      description: |
        Wait for proteins analysis. 
  - plipids:
      type: file
      description: |
        Wait for lipids analysis. 
  - genes:
      type: boolean
      description: |
        Do you have genes?
  - mirna:
      type: boolean
      description: |
        Do you have mirna?
   - proteins:
      type: boolean
      description: |
        Do you have proteins?
  - lipids:
      type: boolean
      description: |
        Do you have lipids?
   - path:
      type: file
      description: |
        Directory where different omics count matrices are stored.
  - samplesinfo:
      type: file
      description: |
        Samples info file containing the attributes of the samples of your count matrices. Samples have to be identical with the column names in your count matrix.
  - a1lim:
      type: string
      description: |
        X axis limits in order to choose integrated features from the samples space from the PCA, generated by MCIA. see MCIA selectVar(). Default: '0,Inf'
  - a2lim:
      type: string
      description: |
        Y axis limits in order to choose integrated features from the samples space from the PCA, generated by MCIA. see MCIA selectVar().  Default: '0,Inf'


output:
  - integrated:
      type: file
      description: |
        Dataframe of integrated features based on the X, Y limits you chose.
  - integratedRdata:
      type: file
      description: |
        Robject of integrated features based on the X, Y limits you chose.
  - pca_integrated:
      type: directory
      description: |
        PCA of integrated features. Based on that you can refine you X, Y choices. 
.
        
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"


authors:
  - "@BiancaPasat"
