name: clusterprofiler
description: Pathway enrichment analysis
keywords:
  - hub genes
  - pathway analysis
  - enrichment analysis
tools:
  - clusterprofiler:
      description: A universal enrichment tool for interpreting omics data.
      homepage: https://bioconductor.org/packages/release/bioc/html/clusterProfiler.html
      documentation: https://bioconductor.org/packages/release/bioc/vignettes/clusterProfiler/inst/doc/clusterProfiler.html
      tool_dev_url: None
      doi: ""
      licence: ["Artistic-2.0 (see package)"]

input:
  - features:
      type: file
      description: |
        List of differentially expressed features
  - alg:
      type: string
      description: |
        Algorithm used to perform differential expression analysis. Option: 'edger', 'rp','deseq2','mcia'
  - genespval:
      type: string
      description: |
        Pvalue cut off for significant genes (Default: 0.05)
    

output:
  - svg plots:
      type: list
      description: |
        Different plots from the pathway and gene enrichment analysis including barplots, cnetplots, dotplots, ematplots, heatplots, treeplots, upsetplot
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"


authors:
  - "@BiancaPasat"
