name: lipidr
description: Data Mining and Analysis of Lipidomics Datasets
keywords:
  - metabolomics
  - lipidomics
  - differential expression 
tools:
  - lipidr:
      description: Data Mining and Analysis of Lipidomics Datasets
      homepage: https://bioconductor.org/packages/release/bioc/html/lipidr.html
      documentation: https://bioconductor.org/packages/release/bioc/vignettes/lipidr/inst/doc/workflow.html
      doi: ""
      licence: ["LGPL (>= 3)"]




input:
  - count_matrix:
      type: file
      description: |
        Count matrix of features you want to estimate the differential expression. Rows are features, columns are samples.
  - samplesInfo:
      type: file
      description: |
        Samples info file containing the attributes of the samples of your count matrix. Condition of interest SHOULD be in the first column. Samples names have to be identical with the column names in your count matrix.
  - lipidr_normalized:
      type: file
      description: |
        Robject from lipidr_normalize
  - formulaformodelmatrix:
    type: string
    description: |
        Formula of your design matrix
  - condition:
      type: string
      description: |
        Which is the condition of interest. It has to be a value in the first column of your samples info file you provided. 




output:
  - de_lipids:
      type: file
      description: |
        Dataframe with differentially expressed features.
  - de_plots:
      type: list
      description: |
        Plots of differentially expressed features.
        
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"


authors:
  - "@BiancaPasat"
