name: edger
description: Differential expression analysis
keywords:
  - differential expression
  - negative binomial
  - rnaseq
tools:
  - edger:
      description: Empirical Analysis of Digital Gene Expression Data in R
      homepage: https://bioconductor.org/packages/release/bioc/html/edgeR.html
      documentation: https://bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/intro.html
      tool_dev_url: None
      doi: ""
      licence: ["GPL (>=2)"]

input:
  - count_matrix:
      type: file
      description: |
        Count matrix of features you want to estimate the differential expression. Rows are features, columns are samples.
  - samplesInfo:
      type: file
      description: |
        Samples info file containing the attributes of the samples of your count matrix. Sample names have to be identical with the column names in your count matrix.
  - groupingfactor:
      type: string
      description: |
        Name of column existing in your samplesinfo file according to which you want to group your samples.
  - formulaformodelmatrix:
      type: string
      description: |
        Formula of your design matrix
  - contrasts:
      type: string
      description: |
        Contrasts you wish to perform. Values have to be cells existing in the column you chose in the groupingfactor. 

output:
  - de_genes:
      type: file
      description: |
        Differentially expressed features.
  - de_features_expressions:
      type: file
      description: |
        Differentially expressed features with count data.
  - de_genesRData:
      type: file
      description: |
        Robject from analysis.
        
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"


authors:
  - "@BiancaPasat"
