name: cut
description: Cut and sed to format outputs of this pipeline
keywords:
  - cut
  - sed
tools:
  - cut:
      description:  Choose first 2 columns, rename to differentiate, remove " and replace space with tab



input:
  - txt:
      type: map
      description: |
        Intermediate files in the align-assembly step


output:
  - cpat_out:
      type: map
      description: |
        Refined results that can be used downstream in this pipeline.
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"


authors:
  - "@BiancaPasat"
